### ISSUE TITLE
Assertion Failure starting lein vimclojure

### ISSUE THREAD

**Issue by colezlaw** [daveray/vimclojure-easy#17]
Did everything up to Starting the Nailgun Server, and when I run `lein vimclojure`, I get the following stacktrace:

```
$ lein vimclojure
Exception in thread "main" java.lang.AssertionError: Assert failed: (vector? (:dependencies project))
    at leiningen.vimclojure$has_vimclojure_dep_QMARK_.invoke(vimclojure.clj:101)
    at leiningen.vimclojure$add_vimclojure_dep.invoke(vimclojure.clj:112)
    at leiningen.vimclojure$vimclojure.doInvoke(vimclojure.clj:189)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$resolve_task$fn__1606.doInvoke(main.clj:132)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$apply_task.invoke(main.clj:167)
    at leiningen.core.main$_main$fn__1665.invoke(main.clj:237)
    at leiningen.core.main$_main.doInvoke(main.clj:221)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

I suspect, it could be a problem with my `~/.lein/profiles.clj`, which didn't exist prior to adding it here.

```
$ cat ~/.lein/profiles.clj 
{:user {:plugins [[lein-tarsier "0.9.1"]]}}
```

And the `project.clj`:

```
$ cat project.clj 
(defproject nailgun-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.4.0"]])
```

I switched to `lein-tarsier` 0.9.4, and still no dice.

**Comment by colezlaw** [comment]
Found the problem from other plugins having similar problems. `leinjacker` needs to be updated. Just added `leinjacker 0.4.1` to my plugins.
