### ISSUE TITLE
Issue with lein-tarsier 0.9.1 and Leiningen 2

### ISSUE THREAD

**Issue by seabre** [daveray/vimclojure-easy#18]
When running `lein vimclojure` I was getting the following output:

```
Exception in thread "main" java.lang.AssertionError: Assert failed: (vector? (:dependencies project))
    at leiningen.vimclojure$has_vimclojure_dep_QMARK_.invoke(vimclojure.clj:101)
    at leiningen.vimclojure$add_vimclojure_dep.invoke(vimclojure.clj:112)
    at leiningen.vimclojure$vimclojure.doInvoke(vimclojure.clj:189)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$resolve_task$fn__1606.doInvoke(main.clj:132)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$apply_task.invoke(main.clj:167)
    at leiningen.core.main$_main$fn__1665.invoke(main.clj:237)
    at leiningen.core.main$_main.doInvoke(main.clj:221)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

Changing:

``` clojure
{:user {:plugins [[lein-tarsier "0.9.1"]]}}
```

To:

``` clojure
 {:user {:plugins [[lein-tarsier "0.10.0"]]}}
```

In `~/.lein/profiles.clj` seems to resolve the issue.

**Comment by daveray** [comment]
Thanks. I updated the version of `lein-tarsier` in the README.
