### ISSUE TITLE
Java code from readme doesn't seem to work

### ISSUE THREAD

**Issue by AWinterman** [daveray/vimclojure-easy#8]
Hi there,

I installed vimclojure via your very helpful instructions. I ran

```
cd
java -cp server-2-3-0.jar:~/path/to/clojure-1.3.0.jar vimclojure-nailgun.NGServer`
```

and see the following errors:

```
Exception in thread "main" java.lang.NoClassDefFoundError: vimclojure-nailgun/NGServer
Caused by: java.lang.ClassNotFoundException: vimclojure-nailgun.NGServer
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

Any idea what could be going wrong?

**Comment by daveray** [comment]
Is server-2.3.0.jar in the current dir? Did you substitute the correct path
for "~/path/to"?
